# Prometheus 配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'blackbox'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.100.4:9100']

  - job_name: 'Linux Node'
    static_configs:
      - targets: ['192.168.100.1:9100','192.168.100.2:9100','192.168.100.3:9100','192.168.100.4:9100','192.168.100.5:9100','192.168.100.6:9100']

  - job_name: 'Windows Node'
    static_configs:
      - targets: ['192.168.100.7:9182']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets: ['192.168.100.1', '192.168.100.2', '192.168.100.3', '192.168.100.4', '192.168.100.5', '192.168.100.6', '192.168.100.7']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.100.9:9115

  - job_name: 'haproxy'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.100.5:9101']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.100.5:9101

  - job_name: 'haproxy_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.100.18:9101', '192.168.100.19:9101']
  
  - job_name: 'coredns'
    metrics_path: /metrics    
    static_configs:
      - targets: ['192.168.100.25:9253']
